/// To solve Day 11, all we need is the list of numbers from the input file.
pub type Input =
  Result(List(Int), String)

/// The results for Day 11 are counts of stones, apparently generated by 
/// blinking. I wonder what happens if we blink slower...
pub type Output =
  Result(Int, String)

pub const input_path = "inputs/day11/input.txt"

pub const example1_path = "test/day11/examples/example1.txt"

pub const example2_path = "test/day11/examples/example2.txt"
